# Generated by Django 4.1.7 on 2023-05-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette_cuisine', '0004_user_alter_recette_image_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
