# Generated by Django 4.1.7 on 2023-05-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette_cuisine', '0005_user_prenom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
