# Generated by Django 4.1.7 on 2023-05-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recette_cuisine', '0006_remove_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
