# Generated by Django 4.1.7 on 2023-05-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette_cuisine', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
