# Generated by Django 4.1.7 on 2023-05-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette_cuisine', '0008_remove_review_created_at_remove_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='recette',
        ),
    ]
