# Generated by Django 4.1.7 on 2023-05-06 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recette_cuisine', '0010_rename_review_review_comment_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recette',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recette_cuisine.recette'),
            preserve_default=False,
        ),
    ]
