# Generated by Django 4.1.7 on 2023-05-06 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recette_cuisine', '0015_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe',
            new_name='recette',
        ),
    ]
